---
- name: Generate new password
  include_tasks: create_password.yml

- name: Creating new user {{ username }}
  user:
    name: "{{ username }}"
    password: "{{ password_hash.stdout_lines[-1] }}"
    state: present
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    update_password: on_create

- name: Copy ssh public key from host to remote for user {{ username }}
  become: true
  copy:
    src: ~/.ssh/id_ed25519.pub
    dest: /home/{{ username }}/.ssh/authorized_keys
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - copy_host_ssh_id
