---
- name: generate new password
  delegate_to: localhost
  command: diceware --no-caps -d '!' -w en_eff
  register: new_password

- file:
    path: "{{ item }}"
    state: directory
  delegate_to: localhost
  with_items:
    - "{{ rpi_password_path }}/{{ inventory_hostname }}"

- name: Store password [REMOVE/SECURE {{ rpi_password_path }}/{{ inventory_hostname }}/pass_{{ username }}]
  delegate_to: localhost
  copy:
    content: "{{ new_password.stdout }}"
    dest: "{{ rpi_password_path }}/{{ inventory_hostname }}/pass_{{ username }}"
    backup: yes
    mode: '0600'

- name: Generate password hash
  delegate_to: localhost
  expect:
    command: mkpasswd --method=sha-512
    responses:
      (?i)password: "{{ new_password.stdout }}"
  register: password_hash

